name: Mis Actions

on:
  push:
  workflow_dispatch:

jobs:
  local-actions:
    runs-on: ubuntu-latest

    steps:
      - name: ğŸšš Checkout repository    # Se hace checkout para que se copien al runnner.
        uses: actions/checkout@v4

      - name: â€ Mi Local Action
        uses: ./.github/actions/my-action   # Ruta donde se encuentra mi GH action.
        with:
          message: 'Ice'                    # Nombre de la variable en mi GH action.

      - name: â Mi Segundo Action
        uses: ./.github/actions/otro-action
